"""empty message

Revision ID: 448272e69b39
Revises: 
Create Date: 2019-06-24 20:23:32.870790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448272e69b39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Contacs', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('serviceitem', sa.Column('icon', sa.TEXT(), nullable=True))
    op.add_column('serviceitem', sa.Column('title', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serviceitem', 'title')
    op.drop_column('serviceitem', 'icon')
    op.alter_column('Contacs', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
